baseURL = "https://matik.space/"
title = "Matik"
languageCode = "cs"
disableKinds = ["taxonomy", "404", "RSS"]
titleCaseStyle = "firstupper"

[params]
  domain = "matik.space"
  author = "Martin Zeman"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

[markup.goldmark.renderer]
  unsafe = true
