baseURL = "https://matik.space/"
title = "matik.space"
languageCode = "cs"
disableKinds = ["taxonomy", "taxonomyTerm", "404", "RSS"]
titleCaseStyle = "firstupper"

[params]
  author = "Martin Zeman"
  disableTags = true
  disableCategories = true
