baseURL = "https://example.com/"
title = "matik.space"
languageCode = "cs"
disableKinds = ["taxonomy", "taxonomyTerm", "404", "RSS"]
titleCaseStyle = "firstupper"

[params]
  author = "Martin Zeman"
  contact = "johndoe@email.com"
  disableTags = true
  disableCategories = true

[build.minify]
  css = true
  js = true
  html = true

disableLiveReload = true
